### ISSUE TITLE
Summary of time for the current day

### ISSUE THREAD

**Issue by ahosgood** [MashSoftware/time-tracker#39] opened 2021-01-08 16:26 UTC
**Is your feature request related to a problem? Please describe.**
Not related to any issue

**Describe the solution you'd like**
A summary of how above/below the current time you are for the current day

**Describe alternatives you've considered**
No alternatives considered

**Additional context**
Mockup of feature request:

<img width="755" alt="Screenshot 2021-01-08 at 16 23 52" src="https://user-images.githubusercontent.com/2356642/104039255-0c83a900-51ce-11eb-947f-8718d1b9f137.png">

**Comment by matthew-shaw** [comment] 2021-01-18 13:11
Related to #22

**Comment by matthew-shaw** [comment] 2021-03-06 23:53
Think this may duplicate #22 as well? Will display time per day alongside daily time delta against schedule.

**Comment by matthew-shaw** [comment] 2022-08-12 00:25
Duplicate of #22

**Closed by matthew-shaw** 2022-08-12 00:25 UTC
Labels: enhancement
